<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StockAtkSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('stock_atk')->insert([
            [
                'name' => 'Bolpen Hitam',
                'unit' => 'pcs',
                'stock_qty' => 0,
                'min_stock' => 0,
                'description' => null,
                'created_at' => '2025-04-19 07:54:55',
                'updated_at' => '2025-04-19 07:54:55',
            ],
            [
                'name' => 'Bolpen Biru',
                'unit' => 'pcs',
                'stock_qty' => 0,
                'min_stock' => 0,
                'description' => null,
                'created_at' => '2025-04-19 07:54:55',
                'updated_at' => '2025-04-19 07:54:55',
            ],
            [
                'name' => 'Bolpen Merah',
                'unit' => 'pcs',
                'stock_qty' => 0,
                'min_stock' => 0,
                'description' => null,
                'created_at' => '2025-04-19 07:54:55',
                'updated_at' => '2025-04-19 07:54:55',
            ],
            [
                'name' => 'Isi staples Kecil',
                'unit' => 'pcs',
                'stock_qty' => 0,
                'min_stock' => 0,
                'description' => null,
                'created_at' => '2025-04-19 07:54:55',
                'updated_at' => '2025-04-19 07:54:55',
            ],
            [
                'name' => 'Isi Staples Besar',
                'unit' => 'pcs',
                'stock_qty' => 0,
                'min_stock' => 0,
                'description' => null,
                'created_at' => '2025-04-19 07:54:55',
                'updated_at' => '2025-04-19 07:54:55',
            ],
            [
                'name' => 'Staples Kecil',
                'unit' => 'pcs',
                'stock_qty' => 0,
                'min_stock' => 0,
                'description' => null,
                'created_at' => '2025-04-19 07:54:55',
                'updated_at' => '2025-04-19 07:54:55',
            ],
            [
                'name' => 'Staples Besar',
                'unit' => 'pcs',
                'stock_qty' => 0,
                'min_stock' => 0,
                'description' => null,
                'created_at' => '2025-04-19 07:54:55',
                'updated_at' => '2025-04-19 07:54:55',
            ],
            [
                'name' => 'Kwitansi',
                'unit' => 'pcs',
                'stock_qty' => 0,
                'min_stock' => 0,
                'description' => null,
                'created_at' => '2025-04-19 07:54:55',
                'updated_at' => '2025-04-19 07:54:55',
            ],
            [
                'name' => 'Buku Tulis',
                'unit' => 'pcs',
                'stock_qty' => 0,
                'min_stock' => 0,
                'description' => null,
                'created_at' => '2025-04-19 07:54:55',
                'updated_at' => '2025-04-19 07:54:55',
            ],
            [
                'name' => 'Lakban Besar',
                'unit' => 'pcs',
                'stock_qty' => 0,
                'min_stock' => 0,
                'description' => null,
                'created_at' => '2025-04-19 07:54:55',
                'updated_at' => '2025-04-19 07:54:55',
            ],
            [
                'name' => 'Isolasi Kecil',
                'unit' => 'pcs',
                'stock_qty' => 0,
                'min_stock' => 0,
                'description' => null,
                'created_at' => '2025-04-19 07:54:55',
                'updated_at' => '2025-04-19 07:54:55',
            ],
            [
                'name' => 'Stipo Cair',
                'unit' => 'pcs',
                'stock_qty' => 0,
                'min_stock' => 0,
                'description' => null,
                'created_at' => '2025-04-19 07:54:55',
                'updated_at' => '2025-04-19 07:54:55',
            ],
            [
                'name' => 'Stipo Kertas',
                'unit' => 'pcs',
                'stock_qty' => 0,
                'min_stock' => 0,
                'description' => null,
                'created_at' => '2025-04-19 07:54:55',
                'updated_at' => '2025-04-19 07:54:55',
            ],
            [
                'name' => 'Cutter Besar',
                'unit' => 'pcs',
                'stock_qty' => 0,
                'min_stock' => 0,
                'description' => null,
                'created_at' => '2025-04-19 07:54:55',
                'updated_at' => '2025-04-19 07:54:55',
            ],
            [
                'name' => 'Isi Cutter',
                'unit' => 'pcs',
                'stock_qty' => 0,
                'min_stock' => 0,
                'description' => null,
                'created_at' => '2025-04-19 07:54:55',
                'updated_at' => '2025-04-19 07:54:55',
            ],
            [
                'name' => 'Gunting',
                'unit' => 'pcs',
                'stock_qty' => 0,
                'min_stock' => 0,
                'description' => null,
                'created_at' => '2025-04-19 07:54:55',
                'updated_at' => '2025-04-19 07:54:55',
            ],
            [
                'name' => 'Penggaris',
                'unit' => 'pcs',
                'stock_qty' => 0,
                'min_stock' => 0,
                'description' => null,
                'created_at' => '2025-04-19 07:54:55',
                'updated_at' => '2025-04-19 07:54:55',
            ],
            [
                'name' => 'Kresek',
                'unit' => 'pcs',
                'stock_qty' => 0,
                'min_stock' => 0,
                'description' => null,
                'created_at' => '2025-04-19 07:54:55',
                'updated_at' => '2025-04-19 07:54:55',
            ],
            [
                'name' => 'Tinta Biru',
                'unit' => 'pcs',
                'stock_qty' => 0,
                'min_stock' => 0,
                'description' => null,
                'created_at' => '2025-04-19 07:54:55',
                'updated_at' => '2025-04-19 07:54:55',
            ],
            [
                'name' => 'Tinta Merah',
                'unit' => 'pcs',
                'stock_qty' => 0,
                'min_stock' => 0,
                'description' => null,
                'created_at' => '2025-04-19 07:54:55',
                'updated_at' => '2025-04-19 07:54:55',
            ],
            [
                'name' => 'Spidol Besar Permanent',
                'unit' => 'pcs',
                'stock_qty' => 0,
                'min_stock' => 0,
                'description' => null,
                'created_at' => '2025-04-19 07:54:55',
                'updated_at' => '2025-04-19 07:54:55',
            ],
            [
                'name' => 'Spidol Besar Boardmaker',
                'unit' => 'pcs',
                'stock_qty' => 0,
                'min_stock' => 0,
                'description' => null,
                'created_at' => '2025-04-19 07:54:55',
                'updated_at' => '2025-04-19 07:54:55',
            ],
            [
                'name' => 'Lem Povinal Kecil',
                'unit' => 'pcs',
                'stock_qty' => 0,
                'min_stock' => 0,
                'description' => null,
                'created_at' => '2025-04-19 07:54:55',
                'updated_at' => '2025-04-19 07:54:55',
            ],
            [
                'name' => 'Lem Povinal Besar 500ml',
                'unit' => 'pcs',
                'stock_qty' => 0,
                'min_stock' => 0,
                'description' => null,
                'created_at' => '2025-04-19 07:54:55',
                'updated_at' => '2025-04-19 07:54:55',
            ],
            [
                'name' => 'Karet Gelang',
                'unit' => 'pcs',
                'stock_qty' => 0,
                'min_stock' => 0,
                'description' => null,
                'created_at' => '2025-04-19 07:54:55',
                'updated_at' => '2025-04-19 07:54:55',
            ],
            [
                'name' => 'Amplop C',
                'unit' => 'pcs',
                'stock_qty' => 0,
                'min_stock' => 0,
                'description' => null,
                'created_at' => '2025-04-19 07:54:55',
                'updated_at' => '2025-04-19 07:54:55',
            ],
            [
                'name' => 'Amplop D',
                'unit' => 'pcs',
                'stock_qty' => 0,
                'min_stock' => 0,
                'description' => null,
                'created_at' => '2025-04-19 07:54:55',
                'updated_at' => '2025-04-19 07:54:55',
            ],
            [
                'name' => 'Amplop E',
                'unit' => 'pcs',
                'stock_qty' => 0,
                'min_stock' => 0,
                'description' => null,
                'created_at' => '2025-04-19 07:54:55',
                'updated_at' => '2025-04-19 07:54:55',
            ]
        ]);
    }
}
